/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dim.encryptiontool.ui;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.SplitPaneUI;
import javax.swing.plaf.basic.BasicSplitPaneUI;
import org.apache.commons.codec.binary.Base64;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author daiyma
 */
public class FrmEncoding extends javax.swing.JPanel {

    final String base64 = "BASE64";
    final String url = "URL";
    final String encoding = "UTF-8";
    File out = null;

    enum Action {

        encode, decode;
    }

    /**
     * Creates new form FrmEncoding
     */
    public FrmEncoding() {
        initComponents();

        jSplitPane1.setOneTouchExpandable(true);//让分割线显示出箭头
        jSplitPane1.setContinuousLayout(true);//操作箭头，重绘图形
        SplitPaneUI ui = jSplitPane1.getUI();
        if (ui instanceof BasicSplitPaneUI) {
            ((BasicSplitPaneUI) ui).getDivider().setBorder(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaSec = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaOri = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbxAlgorithm = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnOutput = new javax.swing.JButton();
        btnCalc = new javax.swing.JButton();

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(128);
        jSplitPane1.setDividerSize(8);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jtaSec.setColumns(20);
        jtaSec.setRows(5);
        jtaSec.setTabSize(6);
        jtaSec.setBorder(javax.swing.BorderFactory.createTitledBorder("密文"));
        jScrollPane2.setViewportView(jtaSec);

        jSplitPane1.setRightComponent(jScrollPane2);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jtaOri.setColumns(20);
        jtaOri.setRows(2);
        jtaOri.setBorder(javax.swing.BorderFactory.createTitledBorder("原文"));
        jScrollPane1.setViewportView(jtaOri);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("编码及算法"));

        jLabel3.setText("算法");

        cbxAlgorithm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Base64", "URL" }));

        jLabel1.setText("显示方式");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("UTF-8");

        jRadioButton2.setText("ANSI");

        jRadioButton3.setText("UNICODE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addGap(0, 48, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("操作"));

        btnOutput.setText("输出到文件(O)");
        btnOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutputActionPerformed(evt);
            }
        });

        btnCalc.setText("编码/解码(C)");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOutput)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutputActionPerformed
        // TODO 输出到文件
        File f = com.dim.IO.FileUtil.chooseFile("请选择输出文件", this);
        out = f;
        if (f != null && f.exists() && f.canWrite()) {
            if (f.length() > 0) {
                int action = JOptionPane.showConfirmDialog(this, "目标文件非空，原文件将被覆盖！",
                        "注意", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, Values.icon_warn);
                if (action == JOptionPane.YES_OPTION) {
                    try {
                        //覆盖源文件
                        btnCalcActionPerformed(null);
                    } catch (Exception ex) {
                        Logger.getLogger(FrmEncoding.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                btnCalcActionPerformed(null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "目标文件不可用 。");
        }

    }//GEN-LAST:event_btnOutputActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO 原文非空做正向编码，否则做解码
        String algorithm = cbxAlgorithm.getSelectedItem().toString();
        if (StringUtils.isNotBlank(jtaOri.getText())) {
            calculate(algorithm, Action.encode);
        } else if (StringUtils.isNotBlank(jtaSec.getText())) {
            calculate(algorithm, Action.decode);
        } else {
            JOptionPane.showMessageDialog(this, "请输入......");
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /*
     * 编解码业务
     */
    private void calculate(String algorithm, Action action) {
        switch (action) {
            case encode:
                encode(algorithm);
                break;
            case decode:
                decode(algorithm);
                break;
            default:
                decode(algorithm);
                break;
        }
    }

    private void encode(String code) {
        String secret = "";
        String ori = jtaOri.getText();
        if (base64.equalsIgnoreCase(code)) {
            secret = Base64.encodeBase64String(ori.getBytes());
        } else {
            try {
                secret = URLEncoder.encode(ori, encoding);
            } catch (UnsupportedEncodingException ex) {
                jtaSec.setText(ex.getClass().getName());
            }
        }
        jtaSec.setText(secret);
        if (out == null) {
            return;
        }
        try {
            FileWriter wr = new FileWriter(out);
            wr.write(secret);
            wr.close();
        } catch (IOException ex) {
            Logger.getLogger(FrmEncoding.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void decode(String code) {
        String ori = "";
        String secret = jtaSec.getText().toString();
        if (base64.equalsIgnoreCase(code)) {
            try {
                ori = new String(Base64.decodeBase64(secret),"UTF-8");
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(FrmEncoding.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                ori = URLDecoder.decode(secret, encoding);
            } catch (UnsupportedEncodingException ex) {
                jtaOri.setText(ex.getClass().getName());
            }
        }
        jtaOri.setText(ori);
        if (out == null) {
            return;
        }
        try {
            FileWriter wr = new FileWriter(out);
            wr.write(ori);
            wr.close();
        } catch (IOException ex) {
            Logger.getLogger(FrmEncoding.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnOutput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxAlgorithm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jtaOri;
    private javax.swing.JTextArea jtaSec;
    // End of variables declaration//GEN-END:variables
}
