/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dim.encryptiontool.ui;

import com.dim.IO.FileUtil;
import com.dim.encryption.DES;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author yanming_dai
 */
public class FrmSymmetric extends javax.swing.JPanel {    
    /**
     * Creates new form PNLPki
     */
    public FrmSymmetric() {
        initComponents();
        init();
    }

    private void init() {
        this.setBackground(Values.B_G);
        
        jbtnSrcChoose.setIcon(Values.icon_open);
        jbtnDstChoose.setIcon(Values.icon_open);
        jbtnEncode.setMnemonic(java.awt.event.KeyEvent.VK_E);
        jbtnDecode.setMnemonic(java.awt.event.KeyEvent.VK_D);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbBoxAlgorithm = new javax.swing.JComboBox();
        txtPwd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chkBoxShellEncrypt = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSrcFile = new javax.swing.JTextField();
        txtDstFile = new javax.swing.JTextField();
        jbtnSrcChoose = new javax.swing.JButton();
        jbtnDstChoose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnEncode = new javax.swing.JButton();
        jbtnDecode = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(586, 300));

        jPanel1.setBackground(Values.B_G);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("算法参数"));

        cmbBoxAlgorithm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DES", "AES" }));
        cmbBoxAlgorithm.setEnabled(false);
        cmbBoxAlgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxAlgorithmActionPerformed(evt);
            }
        });

        txtPwd.setEnabled(false);
        txtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwdActionPerformed(evt);
            }
        });

        jLabel1.setText("密码");

        chkBoxShellEncrypt.setSelected(true);
        chkBoxShellEncrypt.setText("网关脚本加密");
        chkBoxShellEncrypt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBoxShellEncryptStateChanged(evt);
            }
        });
        chkBoxShellEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxShellEncryptActionPerformed(evt);
            }
        });

        jLabel5.setText("加密算法");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPwd)
                            .addComponent(cmbBoxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(chkBoxShellEncrypt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbBoxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkBoxShellEncrypt))
        );

        jPanel2.setBackground(Values.B_G);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("输入输出参数"));

        jLabel2.setText("原文件");

        jLabel3.setText("目标文件");

        jbtnSrcChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-open.gif"))); // NOI18N
        jbtnSrcChoose.setMargin(new java.awt.Insets(0, 14, 2, 14));
        jbtnSrcChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSrcChooseActionPerformed(evt);
            }
        });

        jbtnDstChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-open.gif"))); // NOI18N
        jbtnDstChoose.setMargin(new java.awt.Insets(0, 14, 2, 14));
        jbtnDstChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDstChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDstFile, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(txtSrcFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSrcChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDstChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSrcChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSrcFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnDstChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtDstFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBackground(Values.B_G);

        jbtnEncode.setText("加密(E)");
        jbtnEncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEncodeActionPerformed(evt);
            }
        });

        jbtnDecode.setText("解密(D)");
        jbtnDecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(jbtnEncode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnDecode)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEncode)
                    .addComponent(jbtnDecode))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBoxAlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxAlgorithmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxAlgorithmActionPerformed

    private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwdActionPerformed

    private void jbtnSrcChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSrcChooseActionPerformed
        File src = FileUtil.chooseFile("hello", this);
        if (src != null) {
            txtSrcFile.setText(src.getAbsolutePath());
        }
    }//GEN-LAST:event_jbtnSrcChooseActionPerformed

    /**
     * 加密处理事件
     *
     * @param evt
     */
    private void jbtnEncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEncodeActionPerformed
        // TODO add your handling code here:
        if(!chkBoxShellEncrypt.isSelected()){
              JOptionPane.showMessageDialog(this, "暂不支持自选加密算法。", "错误", JOptionPane.ERROR_MESSAGE);
            return ;
        }

        String srcPath = txtSrcFile.getText();
        String destPath = txtDstFile.getText();

        if (StringUtils.isBlank(srcPath)) {
            JOptionPane.showMessageDialog(this, "请选择要加密的源文件。");
            return;
        } else if (!(new File(srcPath).exists())) {
            JOptionPane.showMessageDialog(this, "源文件不存在。");
            return;
        } else if (new File(srcPath).isDirectory()) {
            JOptionPane.showMessageDialog(this, "只能选择文件。");
            return;
        }
        if (StringUtils.isBlank(destPath)) {
            int action = JOptionPane.showConfirmDialog(this, "您未选择目标文件，原文件将被覆盖。", 
                    "注意", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, Values.icon_warn);
            if (action == JOptionPane.OK_OPTION) {
                //覆盖源文件
                //TODO 异步处理
                encryptFile(srcPath, srcPath);
                txtDstFile.setText(txtSrcFile.getText());
            }
        } else {
            encryptFile(srcPath, destPath);
        }
    }//GEN-LAST:event_jbtnEncodeActionPerformed
    /**
     * 加密文件业务
     *
     * @param srcPath
     * @param destPath
     */
    void encryptFile(String srcPath, String destPath) {
        try {
            DES.encryptFile(srcPath, destPath, DES.pass);
            JOptionPane.showMessageDialog(this, "文件加密完成。");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "加密失败:" + ex.getClass());
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * 解密业务
     *
     * @param srcPath
     * @param destPath
     */
    void decryptFile(String srcPath, String destPath) {
        try {
            DES.decryptFile(srcPath, destPath, DES.pass);
            JOptionPane.showMessageDialog(this, "文件解密完成。");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "解密失败，请确认文件有效性。");
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void chkBoxShellEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxShellEncryptActionPerformed
        // TODO add your handling code here:
        boolean notDefault = !chkBoxShellEncrypt.isSelected();
        txtPwd.setEnabled(notDefault);
        cmbBoxAlgorithm.setEnabled(notDefault);
    }//GEN-LAST:event_chkBoxShellEncryptActionPerformed

    private void chkBoxShellEncryptStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBoxShellEncryptStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxShellEncryptStateChanged

    private void jbtnDstChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDstChooseActionPerformed
        // TODO add your handling code here:
        File dst = FileUtil.chooseFile("hello", this);
        if (dst != null) {
            txtDstFile.setText(dst.getAbsolutePath());
        }
    }//GEN-LAST:event_jbtnDstChooseActionPerformed
    /**
     * 解密处理事件
     *
     * @param evt
     */
    private void jbtnDecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecodeActionPerformed
        if (!chkBoxShellEncrypt.isSelected()) {
            JOptionPane.showMessageDialog(this, "暂不支持自选加密算法。", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String srcPath = txtSrcFile.getText();
        String destPath = txtDstFile.getText();
        if (StringUtils.isBlank(srcPath)) {
            JOptionPane.showMessageDialog(this, "请选择要解密的文件。");
        } else if (StringUtils.isBlank(destPath)) {
            int action = JOptionPane.showConfirmDialog(this, "您未选择目标文件，原文件将被覆盖。", "注意", JOptionPane.OK_CANCEL_OPTION);
            if (JOptionPane.OK_OPTION == action) {
                decryptFile(srcPath, srcPath);
                txtDstFile.setText(txtSrcFile.getText());
            }
        } else {
            decryptFile(srcPath, destPath);
        }
    }//GEN-LAST:event_jbtnDecodeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBoxShellEncrypt;
    private javax.swing.JComboBox cmbBoxAlgorithm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnDecode;
    private javax.swing.JButton jbtnDstChoose;
    private javax.swing.JButton jbtnEncode;
    private javax.swing.JButton jbtnSrcChoose;
    private javax.swing.JTextField txtDstFile;
    private javax.swing.JTextField txtPwd;
    private javax.swing.JTextField txtSrcFile;
    // End of variables declaration//GEN-END:variables
}
